use ai_design_core::ScriptResult;

/// Run a VBA-style macro against SolidWorks by wrapping it in a VBScript
/// (.vbs) file and executing it via `cscript.exe` on Windows.
///
/// SolidWorks exposes a COM automation interface (SldWorks.Application)
/// that can be driven from VBScript. The user-supplied VBA macro code is
/// embedded into a VBScript harness that creates the SolidWorks
/// application object and executes the macro.
///
/// On non-Windows platforms (macOS, Linux) this returns an error because
/// SolidWorks is Windows-only.
pub fn run_solidworks_script(solidworks_path: &str, script: &str) -> Result<ScriptResult, String> {
    #[cfg(not(target_os = "windows"))]
    {
        let _ = (solidworks_path, script);
        Err("SolidWorks is only available on Windows".into())
    }

    #[cfg(target_os = "windows")]
    {
        let vbscript = format!(
            r#"' SolidWorks VBA Macro Runner
' Generated by AI Design System

Dim swApp
Set swApp = CreateObject("SldWorks.Application")

If swApp Is Nothing Then
    WScript.StdErr.WriteLine "ERROR: Could not create SolidWorks Application object"
    WScript.Quit 1
End If

' Make SolidWorks visible (in case it was running headless)
swApp.Visible = True

' User macro code
{user_script}

WScript.StdOut.WriteLine "MACRO_COMPLETE"
"#,
            user_script = script
        );

        let mut temp =
            tempfile::NamedTempFile::new().map_err(|e| format!("Failed to create temp file: {}", e))?;
        let vbs_path = temp.path().with_extension("vbs");
        let script_path = vbs_path.to_string_lossy().to_string();

        // Write to stable path
        let mut file = std::fs::File::create(&script_path)
            .map_err(|e| format!("Failed to create VBScript file: {}", e))?;
        std::io::Write::write_all(&mut file, vbscript.as_bytes())
            .map_err(|e| format!("Failed to write VBScript: {}", e))?;
        std::io::Write::flush(&mut file)
            .map_err(|e| format!("Failed to flush VBScript: {}", e))?;
        drop(file);

        let output = std::process::Command::new("cscript.exe")
            .args(["/nologo", &script_path])
            .output()
            .map_err(|e| format!("Failed to execute cscript.exe: {}", e))?;

        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        // Clean up temp file
        let _ = std::fs::remove_file(&script_path);

        if stdout.contains("MACRO_COMPLETE") || output.status.success() {
            Ok(ScriptResult::success(
                Some(format!("SolidWorks 宏执行成功\n{}", stdout)),
                vec![],
            ))
        } else {
            Ok(ScriptResult::failure(format!(
                "SolidWorks 宏执行失败\nstdout: {}\nstderr: {}",
                stdout, stderr
            )))
        }
    }
}
