// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 全量内置插件注册表 JSON。
Future<String> getBuiltinPlugins() =>
    RustLib.instance.api.crateApiGetBuiltinPlugins();

/// 单个插件能力 JSON；未命中返回 "{}"。
Future<String> getPluginCapabilities({required String pluginId}) =>
    RustLib.instance.api.crateApiGetPluginCapabilities(pluginId: pluginId);

/// Rust 内核版本号，供 App 显示「Rust 内核已连接」状态。
Future<String> rustVersion() => RustLib.instance.api.crateApiRustVersion();
