import '../plugin_sdk/design_plugin.dart';
import '../models/session.dart';
import '../models/software_capabilities.dart';

const builtInPlugins = [
  BuiltInPlugin(id: 'figma', name: 'Figma', category: DesignCategory.web, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建画布','添加矩形','添加文本','设置填充','导出PNG'], fileFormats: ['fig','png','svg'])),
  BuiltInPlugin(id: 'sketch', name: 'Sketch', category: DesignCategory.web, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建画板','添加形状','导出切片','创建组件'], fileFormats: ['sketch','png','svg','pdf'])),
  BuiltInPlugin(id: 'photoshop', name: 'Photoshop', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['图层操作','滤镜','批处理','导出'], fileFormats: ['psd','png','jpg','tiff'])),
  BuiltInPlugin(id: 'illustrator', name: 'Illustrator', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建画板','添加形状','路径操作','导出SVG'], fileFormats: ['ai','eps','svg','pdf'])),
  BuiltInPlugin(id: 'blender', name: 'Blender', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建立方体','创建球体','导出FBX','渲染图像'], fileFormats: ['blend','fbx','obj','glb'])),
  BuiltInPlugin(id: 'sketchup', name: 'SketchUp', category: DesignCategory.interior, scriptLanguage: 'ruby',
    capabilities: SoftwareCapabilities(actions: ['推拉','材质','场景','剖面'], fileFormats: ['skp','dae','kmz','obj'])),
  BuiltInPlugin(id: 'autocad', name: 'AutoCAD', category: DesignCategory.arch, scriptLanguage: 'lisp',
    capabilities: SoftwareCapabilities(actions: ['绘制直线','绘制圆','创建图层','导出DWG'], fileFormats: ['dwg','dxf','pdf'])),
  BuiltInPlugin(id: 'revit', name: 'Revit', category: DesignCategory.arch, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建墙体','创建楼板','放置族','导出IFC'], fileFormats: ['rvt','rfa','ifc','dwg'])),
  BuiltInPlugin(id: 'fusion360', name: 'Fusion 360', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建草图','拉伸','倒角','导出STEP'], fileFormats: ['f3d','step','iges','stl'])),
  BuiltInPlugin(id: 'maya', name: 'Maya', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建模型','绑定骨骼','动画制作','渲染输出','导出FBX'], fileFormats: ['ma','mb','fbx','obj','alembic'])),
  BuiltInPlugin(id: '3dsmax', name: '3ds Max', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建几何体','修改器','材质编辑','MassFX动力学','导出FBX'], fileFormats: ['max','fbx','obj','3ds'])),
  BuiltInPlugin(id: 'cinema4d', name: 'Cinema 4D', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建对象','MoGraph动态图形','动力学模拟','Redshift渲染','导出FBX'], fileFormats: ['c4d','fbx','obj','alembic'])),
  BuiltInPlugin(id: 'indesign', name: 'InDesign', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建文档','文本排版','图像置入','主页设置','导出PDF'], fileFormats: ['indd','idml','pdf','epub'])),
  BuiltInPlugin(id: 'aftereffects', name: 'After Effects', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建合成','添加图层','关键帧动画','应用特效','渲染输出'], fileFormats: ['aep','mogrt','mp4','mov','gif'])),
  BuiltInPlugin(id: 'premierepro', name: 'Premiere Pro', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['导入素材','剪辑片段','添加转场','调色','导出视频'], fileFormats: ['prproj','mp4','mov','xml'])),
  BuiltInPlugin(id: 'xd', name: 'Adobe XD', category: DesignCategory.web, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建画板','添加组件','交互原型','设计规范','导出切图'], fileFormats: ['xd','png','svg','pdf'])),
  BuiltInPlugin(id: 'lightroom', name: 'Lightroom', category: DesignCategory.ad, scriptLanguage: 'lua',
    capabilities: SoftwareCapabilities(actions: ['导入照片','调整曝光','预设应用','批量导出','色彩校正'], fileFormats: ['lrcat','dng','jpg','tiff','raw'])),
  BuiltInPlugin(id: 'animate', name: 'Animate', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建元件','时间轴动画','骨骼绑定','导出HTML5','发布动画'], fileFormats: ['fla','html','gif','mp4','oam'])),
  BuiltInPlugin(id: 'audition', name: 'Audition', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['导入音频','多轨混音','降噪处理','音效添加','导出音频'], fileFormats: ['sesx','wav','mp3','aac'])),
  BuiltInPlugin(id: 'dreamweaver', name: 'Dreamweaver', category: DesignCategory.web, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建页面','代码编辑','实时预览','FTP发布','响应式布局'], fileFormats: ['html','css','js','php','dwt'])),
  BuiltInPlugin(id: 'characteranimator', name: 'Character Animator', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['导入角色','面部捕捉','动作录制','触发器设置','导出视频'], fileFormats: ['chproj','puppet','mp4','mov'])),
  BuiltInPlugin(id: 'fresco', name: 'Fresco', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建画布','矢量绘画','像素笔刷','水彩混合','导出PSD'], fileFormats: ['fresco','psd','png','jpg','svg'])),
  BuiltInPlugin(id: 'dimension', name: 'Dimension', category: DesignCategory.threeD, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['导入模型','材质贴图','灯光设置','场景渲染','导出图像'], fileFormats: ['dn','psd','png','jpg','glb'])),
  BuiltInPlugin(id: 'bridge', name: 'Bridge', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['浏览文件','批量重命名','元数据编辑','关键词标记','文件排序'], fileFormats: ['jpg','png','psd','raw','pdf'])),
  BuiltInPlugin(id: 'acrobat', name: 'Acrobat Pro', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['创建PDF','编辑文本','合并文档','表单制作','OCR识别'], fileFormats: ['pdf','docx','xlsx','pptx','jpg'])),
  BuiltInPlugin(id: 'substancepainter', name: 'Substance 3D Painter', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['导入模型','UV编辑','纹理绘制','材质烘焙','导出贴图'], fileFormats: ['spp','glb','fbx','obj','png'])),
  BuiltInPlugin(id: 'substancedesigner', name: 'Substance 3D Designer', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['节点编辑','材质生成','程序纹理','函数图表','导出SBSAR'], fileFormats: ['sbs','sbsar','png','tiff','exr'])),
  BuiltInPlugin(id: 'substancesampler', name: 'Substance 3D Sampler', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['照片扫描','材质生成','HDR环境','通道提取','导出材质'], fileFormats: ['sbsar','png','jpg','exr','hdr'])),
  BuiltInPlugin(id: 'substancestager', name: 'Substance 3D Stager', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['场景搭建','模型摆放','材质分配','灯光渲染','导出图像'], fileFormats: ['stager','glb','png','psd','jpg'])),
  BuiltInPlugin(id: 'substancemodeler', name: 'Substance 3D Modeler', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['VR雕刻','粘土建模','布尔运算','网格重构','导出模型'], fileFormats: ['sm3d','glb','fbx','obj','usd'])),
  BuiltInPlugin(id: 'mediaencoder', name: 'Media Encoder', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['导入队列','格式转换','预设应用','批量渲染','监视文件夹'], fileFormats: ['mp4','mov','avi','wav','jpg'])),
  BuiltInPlugin(id: 'incopy', name: 'InCopy', category: DesignCategory.ad, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['编写文案','协同编辑','样式应用','修订追踪','导出文本'], fileFormats: ['icml','incx','docx','txt','rtf'])),
  BuiltInPlugin(id: 'express', name: 'Adobe Express', category: DesignCategory.web, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['模板选择','快速设计','品牌套用','社交图片','导出发布'], fileFormats: ['jpg','png','mp4','pdf','gif'])),
  BuiltInPlugin(id: 'zw3d', name: '中望3D', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建草图','特征建模','装配设计','工程图','导出STEP'], fileFormats: ['zw3d','step','iges','stl','dwg'])),
  BuiltInPlugin(id: '3done', name: '3D One系列', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建模型','拉伸','旋转','阵列','导出STL'], fileFormats: ['3done','stl','obj'])),
  BuiltInPlugin(id: 'voxeldance', name: 'VoxelDance Additive', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型导入','支撑生成','切片','路径规划','导出GCode'], fileFormats: ['vda','stl','gcode','3mf'])),
  BuiltInPlugin(id: 'happy3d', name: 'Happy3D', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建模型','场景编辑','材质贴图','渲染','导出GLB'], fileFormats: ['h3d','glb','stl','obj'])),
  BuiltInPlugin(id: 'maodou3d', name: '毛豆科技3D建模软件', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['创建模型','场景搭建','材质编辑','导出STL'], fileFormats: ['md3d','stl','obj'])),
  BuiltInPlugin(id: 'makerlab', name: 'MakerLab', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型导入','切片','打印管理','模型库','导出GCode'], fileFormats: ['stl','3mf','gcode'])),
  BuiltInPlugin(id: 'crealitycloud', name: 'Creality Cloud', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型上传','云端切片','远程打印','模型库','导出GCode'], fileFormats: ['stl','3mf','gcode'])),
  BuiltInPlugin(id: 'flashprint', name: 'FlashPrint', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型导入','切片配置','支撑编辑','打印预览','导出GCode'], fileFormats: ['stl','obj','3mf','gcode','fpp'])),
  BuiltInPlugin(id: 'flashstudio', name: 'Flash Studio', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型编辑','支撑生成','切片','打印管理','导出GCode'], fileFormats: ['stl','obj','gcode'])),
  BuiltInPlugin(id: 'snapmakerluban', name: 'Snapmaker Luban', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型导入','CNC雕刻','激光切割','3D打印','导出GCode'], fileFormats: ['stl','svg','nc','gcode'])),
  BuiltInPlugin(id: 'snapmakerorca', name: 'Snapmaker Orca', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型导入','切片配置','校准工具','打印管理','导出GCode'], fileFormats: ['stl','3mf','gcode'])),
  BuiltInPlugin(id: 'buildplanner', name: 'Build Planner', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['模型排布','打印队列','材料估算','时间预估','导出布局'], fileFormats: ['stl','layout','gcode'])),
  BuiltInPlugin(id: 'flashdental', name: 'FlashDental', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['牙模导入','模型编辑','支撑生成','切片','导出GCode'], fileFormats: ['stl','3mf','gcode'])),
  BuiltInPlugin(id: 'waxjetprint', name: 'WaxJetPrint', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['蜡模导入','模型优化','支撑生成','切片','导出GCode'], fileFormats: ['stl','wax','gcode'])),
  BuiltInPlugin(id: 'kujiale', name: '酷家乐', category: DesignCategory.interior, scriptLanguage: 'javascript',
    capabilities: SoftwareCapabilities(actions: ['户型绘制','硬装设计','家具布置','效果图渲染','导出全景图'], fileFormats: ['kujiale','json','jpg','png','全景图'])),
  BuiltInPlugin(id: '3vjia', name: '三维家', category: DesignCategory.interior, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['户型导入','定制家具','材质编辑','VR渲染','导出CAD'], fileFormats: ['3vjia','json','obj','dwg','jpg'])),
  BuiltInPlugin(id: 'yuanfang', name: '圆方', category: DesignCategory.interior, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['空间规划','家具布局','材质替换','效果渲染','导出报价单'], fileFormats: ['yuanfang','dwg','jpg','xls'])),
  BuiltInPlugin(id: 'solidworks', name: 'SolidWorks', category: DesignCategory.industrial, scriptLanguage: 'vba',
    capabilities: SoftwareCapabilities(actions: ['创建草图','特征建模','装配设计','生成工程图','导出STEP'], fileFormats: ['sldprt','sldasm','step','iges','dwg'])),
  BuiltInPlugin(id: 'freecad', name: 'FreeCAD', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['参数化建模','草图编辑','零件设计','装配约束','导出STL'], fileFormats: ['fcstd','stl','step','iges','dwg'])),
  BuiltInPlugin(id: 'openscad', name: 'OpenSCAD', category: DesignCategory.industrial, scriptLanguage: 'scad',
    capabilities: SoftwareCapabilities(actions: ['参数化脚本','布尔运算','线性拉伸','旋转体','渲染导出'], fileFormats: ['scad','stl','dxf','svg','off'])),
  BuiltInPlugin(id: 'rhino', name: 'Rhino', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['NURBS建模','曲面编辑','网格重建','渲染导出','Grasshopper参数化'], fileFormats: ['3dm','step','iges','stl','obj'])),
  BuiltInPlugin(id: 'tinkercad', name: 'Tinkercad', category: DesignCategory.industrial, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['导入STL','形状组合','布尔运算','电路仿真','导出STL'], fileFormats: ['stl','obj','svg','brd'])),
  BuiltInPlugin(id: 'meshy', name: 'Meshy', category: DesignCategory.threeD, scriptLanguage: 'python',
    capabilities: SoftwareCapabilities(actions: ['文字生成3D模型','图片生成模型','模型优化','纹理生成','多格式导出'], fileFormats: ['glb','fbx','obj','usd','stl'])),
  BuiltInPlugin(id: 'cura', name: 'UltiMaker Cura', category: DesignCategory.industrial, scriptLanguage: 'cli',
    capabilities: SoftwareCapabilities(actions: ['模型导入','切片配置','支撑设置','打印预览','导出GCode'], fileFormats: ['stl','3mf','gcode','obj'])),
  BuiltInPlugin(id: 'prusaslicer', name: 'PrusaSlicer', category: DesignCategory.industrial, scriptLanguage: 'cli',
    capabilities: SoftwareCapabilities(actions: ['模型导入','切片配置','支撑生成','多色打印','导出GCode'], fileFormats: ['stl','3mf','gcode','obj'])),
  BuiltInPlugin(id: 'orcaslicer', name: 'OrcaSlicer', category: DesignCategory.industrial, scriptLanguage: 'cli',
    capabilities: SoftwareCapabilities(actions: ['模型导入','切片配置','流量校准','支撑编辑','导出GCode'], fileFormats: ['stl','3mf','gcode','obj'])),
  BuiltInPlugin(id: 'simplify3d', name: 'Simplify3D', category: DesignCategory.industrial, scriptLanguage: 'cli',
    capabilities: SoftwareCapabilities(actions: ['模型导入','切片配置','多进程设置','支撑编辑','导出GCode'], fileFormats: ['stl','obj','gcode','3mf'])),
  BuiltInPlugin(id: 'chitubox', name: 'ChiTuBox', category: DesignCategory.industrial, scriptLanguage: 'cli',
    capabilities: SoftwareCapabilities(actions: ['模型导入','树脂切片','支撑生成','镂空挖孔','导出CTB'], fileFormats: ['stl','3mf','ctb','photon'])),
  BuiltInPlugin(id: 'lychee', name: 'Lychee Slicer', category: DesignCategory.industrial, scriptLanguage: 'cli',
    capabilities: SoftwareCapabilities(actions: ['模型导入','树脂切片','支撑编辑','镂空挖孔','导出LYS'], fileFormats: ['stl','obj','lys','ctb'])),
];

const softwareIcons = <String, String>{
  'figma': '🎨', 'sketch': '✏️', 'photoshop': '🖼️', 'illustrator': '🖋️',
  'blender': '🔷', 'sketchup': '🏠', 'autocad': '📐', 'revit': '🏗️',
  'fusion360': '⚙️', 'maya': '🎬', '3dsmax': '🏢', 'cinema4d': '🎥',
  'indesign': '📰', 'aftereffects': '✨', 'premierepro': '🎞️', 'xd': '🧩',
  'lightroom': '📷', 'animate': '🎮', 'audition': '🎵', 'dreamweaver': '🌐',
  'characteranimator': '🤖', 'fresco': '🖌️', 'dimension': '📦', 'bridge': '📂',
  'acrobat': '📄', 'substancepainter': '🎯', 'substancedesigner': '🧬',
  'substancesampler': '📸', 'substancestager': '🎪', 'substancemodeler': '🗿',
  'mediaencoder': '🔄', 'incopy': '📝', 'express': '🚀',
  'zw3d': '🔧', '3done': '🧒', 'voxeldance': '🦴',
  'happy3d': '😊', 'maodou3d': '🫘', 'makerlab': '🧪', 'crealitycloud': '☁️',
  'flashprint': '⚡', 'flashstudio': '💡', 'snapmakerluban': '🖨️',
  'snapmakerorca': '🐋', 'buildplanner': '📋', 'flashdental': '🦷',
  'waxjetprint': '🕯️', 'kujiale': '🏘️', '3vjia': '🏡', 'yuanfang': '📏',
  'solidworks': '🔩', 'freecad': '🧰', 'openscad': '📜', 'rhino': '🦏',
  'tinkercad': '🔺', 'meshy': '🧠', 'cura': '🧵', 'prusaslicer': '🍅',
  'orcaslicer': '🐳', 'simplify3d': '🛠️', 'chitubox': '💧', 'lychee': '🍒',
};

const softwareDescriptions = <String, String>{
  'figma': 'UI 设计软件插件，支持创建画布、图层操作、导出等',
  'sketch': 'macOS UI 设计工具插件，支持画板、图层、导出',
  'photoshop': '图像处理软件插件，支持图层、滤镜、批处理',
  'illustrator': '矢量图形设计软件插件，支持画板、路径、效果',
  'blender': '3D 建模软件插件，支持建模、渲染、导出等',
  'sketchup': '3D 建模软件插件，推拉、材质、场景、剖面',
  'autocad': 'CAD 软件插件，支持绘图、标注、图层管理',
  'revit': 'BIM 建筑设计软件插件，支持墙体、楼板、族、参数',
  'fusion360': '工业设计CAD/CAM软件插件，支持草图、建模、装配',
  'maya': '3D动画与建模软件插件，支持建模、绑定、动画、渲染',
  '3dsmax': '3D建模与渲染软件插件，支持几何体、修改器、动力学',
  'cinema4d': '3D动态图形软件插件，支持MoGraph、动力学、Redshift渲染',
  'indesign': '桌面出版软件插件，支持文档排版、主页、导出PDF/EPUB',
  'aftereffects': '动态图形与视觉特效软件插件，支持合成、关键帧动画、特效渲染',
  'premierepro': '专业视频编辑软件插件，支持多轨剪辑、调色、音频混音、导出',
  'xd': 'UI/UX设计软件插件，支持画板、交互原型、设计规范、切图导出',
  'lightroom': '数字照片管理与编辑软件插件，支持批量调色、预设、RAW处理',
  'animate': '2D交互动画制作软件插件，支持元件动画、骨骼绑定、HTML5导出',
  'audition': '专业音频编辑软件插件，支持多轨混音、降噪、音效处理',
  'dreamweaver': '网页设计与代码编辑器插件，支持可视化布局、代码编辑、FTP发布',
  'characteranimator': '2D角色动画软件插件，支持面部捕捉、动作录制、实时驱动',
  'fresco': '数字绘画与插画软件插件，支持矢量和像素笔刷、水彩混合',
  'dimension': '3D产品设计软件插件，支持模型渲染、材质贴图、场景灯光',
  'bridge': '数字资产管理软件插件，支持文件浏览、批量重命名、元数据管理',
  'acrobat': 'PDF编辑与文档处理插件，支持创建、编辑、合并、表单、OCR',
  'substancepainter': '3D纹理绘制软件插件，支持UV编辑、材质烘焙、智能遮罩',
  'substancedesigner': '3D材质创作软件插件，支持节点材质编辑、程序纹理、函数图表',
  'substancesampler': '3D材质采集软件插件，支持照片扫描、HDR环境、AI材质生成',
  'substancestager': '3D场景搭建软件插件，支持模型摆放、材质分配、灯光渲染',
  'substancemodeler': 'VR 3D建模软件插件，支持粘土雕刻、布尔运算、网格重构',
  'mediaencoder': '媒体转码软件插件，支持格式转换、预设应用、批量渲染',
  'incopy': '协同文案编辑软件插件，支持样式应用、修订追踪、与InDesign联动',
  'express': '快速设计工具插件，支持模板设计、品牌套用、社交图片一键生成',
  'zw3d': '国产CAD/CAM软件插件，支持草图、特征建模、装配、工程图',
  '3done': '青少年3D设计软件插件，支持建模、拉伸、旋转、阵列',
  'voxeldance': '增材制造数据准备软件插件，支撑生成、切片、路径规划',
  'happy3d': '3D建模软件插件，支持场景编辑、材质贴图、渲染导出',
  'maodou3d': '教育3D建模软件插件，支持模型创建、场景搭建、材质编辑',
  'makerlab': '3D打印管理平台插件，支持切片、打印管理、模型库',
  'crealitycloud': '云端3D打印平台插件，支持模型上传、云端切片、远程打印',
  'flashprint': '3D打印切片软件插件，支持切片配置、支撑编辑、打印预览',
  'flashstudio': '3D打印管理软件插件，支持模型编辑、支撑生成、打印管理',
  'snapmakerluban': '多功能CAM软件插件，支持CNC雕刻、激光切割、3D打印',
  'snapmakerorca': '3D打印切片软件插件，基于OrcaSlicer，支持校准、打印管理',
  'buildplanner': '3D打印排布软件插件，支持模型排布、材料估算、时间预估',
  'flashdental': '牙科3D打印软件插件，支持牙模导入、模型编辑、切片',
  'waxjetprint': '蜡模3D打印软件插件，支持蜡模导入、模型优化、切片',
  'kujiale': '云设计室内装修软件插件，支持户型绘制、硬装定制、家具布置、全景渲染',
  '3vjia': '3D家居设计软件插件，支持户型导入、定制家具、材质编辑、VR全景渲染',
  'yuanfang': '室内家具设计软件插件，支持空间规划、家具布局、材质替换、效果图与报价',
  'solidworks': '三维CAD设计软件插件，支持参数化建模、装配设计、工程图',
  'freecad': '开源参数化CAD软件插件，支持零件设计、装配约束、导出STL/STEP',
  'openscad': '程序化CAD软件插件，支持脚本建模、布尔运算、参数化设计',
  'rhino': 'NURBS曲面建模软件插件，支持曲面设计、网格重建、Grasshopper参数化',
  'tinkercad': '在线3D设计工具插件，支持形状组合、布尔运算、电路仿真',
  'meshy': 'AI 3D模型生成平台插件，支持文字/图片生成模型、纹理生成',
  'cura': '开源FDM切片软件插件，支持模型导入、切片配置、支撑设置',
  'prusaslicer': 'FDM/树脂切片软件插件，支持多色打印、支撑生成、打印配置',
  'orcaslicer': '高性能切片软件插件，支持流量校准、多材料、精细支撑',
  'simplify3d': '专业3D打印切片软件插件，支持多进程设置、精细支撑控制',
  'chitubox': '树脂3D打印切片软件插件，支持镂空挖孔、支撑生成、CTB导出',
  'lychee': '树脂3D打印切片软件插件，支持智能支撑、镂空挖孔、LYS导出',
};
