import 'dart:async';
import 'dart:io';
import 'package:logging/logging.dart';
import 'agent_backend.dart';
import 'cc_runner.dart';
import 'text_codec.dart';

final _log = Logger('CliAgentBackend');

/// 通用 CLI agent 后端：OpenCode / OpenClaw / Hermes / Reasonix。
/// 这些 CLI 的调用模式一致（单条 prompt 参数 + 可选 --model），
/// 用配置实例化而非为每个 agent 写一个文件。
class CliAgentBackend implements AgentBackend {
  CliAgentBackend({
    required this.id,
    required this.displayName,
    required this.command,
    required this.args,
    this.modelArgs = _noModelArgs,
    this.apiKeyEnv,
    this.apiKey,
  });

  @override
  final String id;
  @override
  final String displayName;
  final String command;

  /// 构建命令参数：以 prompt 结尾，如 ['run', prompt]。
  final List<String> Function(String prompt) args;

  /// 模型参数：model 为 null 时返回空列表。
  final List<String> Function(String? model) modelArgs;

  /// 可选 API key 环境变量名（如 OPENAI_API_KEY）。
  final String? apiKeyEnv;
  final String? apiKey;

  final Map<String, Process> _processes = {};

  static const _timeout = Duration(seconds: 180);

  /// Windows 命令行上限 32K：超长 prompt 会抛参数过长异常，截断到 20K。
  static const _maxPromptChars = 20000;

  static List<String> _noModelArgs(String? model) => const [];

  static String _limitPrompt(String prompt) {
    if (prompt.length <= _maxPromptChars) return prompt;
    return '${prompt.substring(0, _maxPromptChars)}…[截断]';
  }

  @override
  String? get defaultModel => null;

  @override
  Future<bool> isAvailable() async {
    try {
      final result = await Process.run(
        command,
        ['--version'],
      ).timeout(const Duration(seconds: 10));
      return result.exitCode == 0;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<CCResult> execute({
    required String task,
    required String software,
    required Map<String, dynamic> capabilities,
    required Map<String, dynamic> state,
    String? model,
    String? scriptLanguage,
    String? key,
  }) async {
    final prompt = _limitPrompt(buildCodeBlockPrompt(
      task: task,
      software: software,
      capabilities: capabilities,
      state: state,
      scriptLanguage: scriptLanguage ?? 'javascript',
    ));
    final taskKey = key ?? 'default';
    Process? process;
    try {
      process = await Process.start(
        command,
        [...args(prompt), ...modelArgs(model)],
        environment: {
          ...Platform.environment,
          if (apiKeyEnv != null && apiKey != null && apiKey!.isNotEmpty)
            apiKeyEnv!: apiKey!,
        },
      );
      _processes.remove(taskKey)?.kill();
      _processes[taskKey] = process;

      final stdoutFuture =
          process.stdout.fold<List<int>>(<int>[], (acc, chunk) => acc..addAll(chunk));
      final stderrFuture =
          process.stderr.fold<List<int>>(<int>[], (acc, chunk) => acc..addAll(chunk));
      // 立即关闭 stdin：prompt 走参数，不关 stdin 会挂起等待输入。
      process.stdin.close();

      final exitCode = await process.exitCode.timeout(_timeout);
      final results = await Future.wait([stdoutFuture, stderrFuture]).timeout(_timeout);
      // 同 key 可能已被新任务替换，只移除自己注册的实例。
      if (identical(_processes[taskKey], process)) {
        _processes.remove(taskKey);
      }
      final output = decodeConsoleOutput(results[0]).trim();
      final errors = decodeConsoleOutput(results[1]).trim();

      if (exitCode != 0) {
        return CCResult.failure(
          '$displayName exited with code $exitCode'
          '${errors.isNotEmpty ? ': $errors' : ''}',
        );
      }
      if (output.isEmpty) {
        return CCResult.failure(errors.isNotEmpty ? errors : 'No output from $displayName');
      }
      final script = extractScriptFromMarkdown(output);
      if (script != null) {
        return CCResult(script: script, explanation: 'Generated by $displayName', modelUsed: model);
      }
      return CCResult(script: output, explanation: '$displayName raw output', modelUsed: model);
    } catch (e) {
      // 只清理自己注册的实例：同 key 已被替换时不误杀新任务。
      if (identical(_processes[taskKey], process)) {
        _processes.remove(taskKey);
      }
      if (process != null) {
        await terminateProcess(process);
      }
      _log.severe('$displayName execution failed: $e');
      return CCResult.failure('$displayName execution failed: $e');
    }
  }

  @override
  void cancel({String? key}) {
    if (key != null) {
      _processes.remove(key)?.kill();
      return;
    }
    for (final p in _processes.values) {
      p.kill();
    }
    _processes.clear();
  }
}

/// OpenCode：`opencode run <prompt>`，--auto 免审批（CI 模式）。
final openCodeBackend = CliAgentBackend(
  id: 'opencode',
  displayName: 'OpenCode',
  command: 'opencode',
  args: (p) => ['run', '--auto', p],
  modelArgs: (m) => m == null ? const [] : ['--model', m],
);

/// OpenClaw：`openclaw agent --message <prompt>` 单轮执行。
final openClawBackend = CliAgentBackend(
  id: 'openclaw',
  displayName: 'OpenClaw',
  command: 'openclaw',
  args: (p) => ['agent', '--message', p],
  modelArgs: (m) => m == null ? const [] : ['--model', m],
);

/// Hermes (Nous Research)：`hermes chat -q <prompt>` 单查询模式。
final hermesBackend = CliAgentBackend(
  id: 'hermes',
  displayName: 'Hermes',
  command: 'hermes',
  args: (p) => ['chat', '-q', p],
  modelArgs: (m) => m == null ? const [] : ['--model', m],
);

/// Reasonix (DeepSeek)：`reasonix run <prompt>` 无头执行，--auto 免审批。
final reasonixBackend = CliAgentBackend(
  id: 'reasonix',
  displayName: 'Reasonix',
  command: 'reasonix',
  args: (p) => ['run', '--auto', p],
  modelArgs: (m) => m == null ? const [] : ['--model', m],
);
