import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:logging/logging.dart';
import 'agent_backend.dart';
import 'cc_runner.dart';
import 'text_codec.dart';

final _log = Logger('GeminiBackend');

/// Google Gemini CLI 后端：gemini -p 单轮提示，优先解析 {"text": ...}，
/// 失败时回退提取 markdown 代码块。
class GeminiBackend implements AgentBackend {
  GeminiBackend({this.apiKey});

  /// 可选 GEMINI_API_KEY；未提供时使用 gemini CLI 自身的登录凭证。
  final String? apiKey;
  final Map<String, Process> _processes = {};

  /// Windows 命令行上限 32K：超长 prompt 会抛参数过长异常，截断到 20K。
  static const _maxPromptChars = 20000;

  @override
  String get id => 'gemini';

  @override
  String get displayName => 'Gemini';

  @override
  String? get defaultModel => null;

  @override
  Future<bool> isAvailable() async {
    try {
      final result = await Process.run(
        'gemini',
        ['--version'],
      ).timeout(const Duration(seconds: 10));
      return result.exitCode == 0;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<CCResult> execute({
    required String task,
    required String software,
    required Map<String, dynamic> capabilities,
    required Map<String, dynamic> state,
    String? model,
    String? scriptLanguage,
    String? key,
  }) async {
    final prompt = _limitPrompt(buildCodeBlockPrompt(
      task: task,
      software: software,
      capabilities: capabilities,
      state: state,
      scriptLanguage: scriptLanguage ?? 'javascript',
    ));
    final taskKey = key ?? 'default';
    Process? process;
    try {
      process = await Process.start(
        'gemini',
        ['-p', prompt],
        environment: {
          ...Platform.environment,
          if (apiKey != null && apiKey!.isNotEmpty) 'GEMINI_API_KEY': apiKey!,
        },
      );
      _processes.remove(taskKey)?.kill();
      _processes[taskKey] = process;

      final stdoutFuture =
          process.stdout.fold<List<int>>(<int>[], (acc, chunk) => acc..addAll(chunk));
      final stderrFuture =
          process.stderr.fold<List<int>>(<int>[], (acc, chunk) => acc..addAll(chunk));
      process.stdin.close();

      final exitCode = await process.exitCode.timeout(timeout);
      final results = await Future.wait([stdoutFuture, stderrFuture]).timeout(timeout);
      // 同 key 可能已被新任务替换，只移除自己注册的实例。
      if (identical(_processes[taskKey], process)) {
        _processes.remove(taskKey);
      }
      final output = decodeConsoleOutput(results[0]).trim();
      final errors = decodeConsoleOutput(results[1]).trim();

      if (exitCode != 0) {
        return CCResult.failure(
          'Gemini exited with code $exitCode'
          '${errors.isNotEmpty ? ': $errors' : ''}',
        );
      }
      if (output.isEmpty) {
        return CCResult.failure(errors.isNotEmpty ? errors : 'No output from Gemini');
      }
      final script = _extractScript(output);
      if (script != null) {
        return CCResult(script: script, explanation: 'Generated by Gemini', modelUsed: model);
      }
      return CCResult.failure('No script found in Gemini output');
    } catch (e) {
      // 只清理自己注册的实例：同 key 已被替换时不误杀新任务。
      if (identical(_processes[taskKey], process)) {
        _processes.remove(taskKey);
      }
      if (process != null) {
        await terminateProcess(process);
      }
      _log.severe('Gemini execution failed: $e');
      return CCResult.failure('Gemini execution failed: $e');
    }
  }

  @override
  void cancel({String? key}) {
    if (key != null) {
      _processes.remove(key)?.kill();
      return;
    }
    for (final p in _processes.values) {
      p.kill();
    }
    _processes.clear();
  }

  /// 优先解析 JSON 文本字段，其次提取 markdown 代码块。
  String? _extractScript(String output) {
    if (output.startsWith('{')) {
      try {
        final json = jsonDecode(output) as Map<String, dynamic>;
        final text = json['text'] as String?;
        if (text != null && text.trim().isNotEmpty) {
          return extractScriptFromMarkdown(text) ?? text.trim();
        }
      } catch (_) {
        // 不是合法 JSON，走代码块提取。
      }
    }
    return extractScriptFromMarkdown(output);
  }

  static const timeout = Duration(seconds: 180);

  static String _limitPrompt(String prompt) {
    if (prompt.length <= _maxPromptChars) return prompt;
    return '${prompt.substring(0, _maxPromptChars)}…[截断]';
  }
}
