import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'agent_backend.dart';
import 'cc_runner.dart';

/// 远程端点后端：通过 OpenAI 兼容 /chat/completions 协议请求远程服务生成脚本。
class RemoteBackend implements AgentBackend {
  RemoteBackend({
    required this.endpointUrl,
    required this.apiKey,
    String? model,
    http.Client? client,
    this.timeout = const Duration(seconds: 120),
  })  : _model = model,
        _client = client ?? http.Client();

  final String endpointUrl;
  final String apiKey;
  final String? _model;
  final Duration timeout;
  final http.Client _client;

  /// 已取消任务集合：cancel(key) 只影响该 key 的任务，不影响后续新任务。
  final Map<String, bool> _cancelled = {};
  static const _defaultCancelKey = 'default';

  @override
  String get id => 'remote';

  @override
  String get displayName => 'Remote Endpoint';

  @override
  String? get defaultModel => _model;

  /// 已配置 URL 即视为可用；真正连通性由 execute 的请求结果体现。
  @override
  Future<bool> isAvailable() async => endpointUrl.trim().isNotEmpty;

  @override
  void cancel({String? key}) => _cancelled[key ?? _defaultCancelKey] = true;

  /// 关闭底层 HTTP 客户端，释放连接资源。
  void dispose() => _client.close();

  /// 请求 OpenAI 兼容 /chat/completions 端点并提取生成的脚本。
  @override
  Future<CCResult> execute({
    required String task,
    required String software,
    required Map<String, dynamic> capabilities,
    required Map<String, dynamic> state,
    String? model,
    String? scriptLanguage,
    String? key,
  }) async {
    final cancelKey = key ?? _defaultCancelKey;
    if (_cancelled[cancelKey] ?? false) {
      return CCResult.failure('Remote endpoint cancelled');
    }
    // Uri 解析与 HTTPS 校验放入 try：非法 URL 与其余请求失败统一走 failure 路径。
    try {
      final uri = Uri.parse(_chatCompletionsUrl(endpointUrl));
      if (uri.scheme != 'https' && !_isLoopback(uri.host)) {
        return CCResult.failure('远程端点要求 HTTPS');
      }
      final prompt = buildCodeBlockPrompt(
        task: task,
        software: software,
        capabilities: capabilities,
        state: state,
        scriptLanguage: scriptLanguage ?? 'javascript',
      );
      final body = {
        if (model != null && model.isNotEmpty) 'model': model,
        'messages': [
          {'role': 'system', 'content': prompt},
          {'role': 'user', 'content': task},
        ],
      };
      final response = await _client
          .post(
            uri,
            headers: {
              'Content-Type': 'application/json',
              if (apiKey.isNotEmpty) 'Authorization': 'Bearer $apiKey',
            },
            body: jsonEncode(body),
          )
          .timeout(timeout);
      if (_cancelled[cancelKey] ?? false) {
        return CCResult.failure('Remote endpoint cancelled');
      }
      if (response.statusCode != 200) {
        return CCResult.failure(
            'Remote endpoint error ${response.statusCode}: ${_truncate(response.body)}');
      }
      final content = _extractContent(response.body);
      if (content == null) {
        return CCResult.failure(
            'Remote endpoint returned no script: ${_truncate(response.body)}');
      }
      final script = extractScriptFromMarkdown(content) ?? content.trim();
      if (script.isEmpty) {
        return CCResult.failure('Remote endpoint returned an empty script');
      }
      return CCResult(
        script: script,
        explanation: 'Generated by remote endpoint',
        modelUsed: model ?? _model,
      );
    } catch (e) {
      return CCResult.failure('Remote endpoint request failed: $e');
    } finally {
      // 取消标记只对本次请求生效，请求结束后清除，不影响后续新任务。
      _cancelled.remove(cancelKey);
    }
  }

  /// 以 /chat/completions 结尾的 URL 原样使用，否则在 path 末尾追加。
  /// 用 Uri 组装：query/fragment 拼进 path（?x=1/chat/completions）或
  /// 尾斜杠 URL 重复追加（/chat/completions/chat/completions）都会打错端点。
  String _chatCompletionsUrl(String base) {
    final trimmed = base.trim();
    if (trimmed.endsWith('/chat/completions')) return trimmed;
    final uri = Uri.tryParse(trimmed);
    if (uri == null) return '$trimmed/chat/completions';
    final basePath = uri.path.isEmpty ? '' : uri.path.replaceAll(RegExp(r'/+$'), '');
    if (basePath.endsWith('/chat/completions')) {
      return uri.replace(path: basePath).toString();
    }
    final newPath = basePath.isEmpty ? '/chat/completions' : '$basePath/chat/completions';
    return uri.replace(path: newPath).toString();
  }

  /// 本地回环地址允许明文 http，其余端点强制 https。
  static bool _isLoopback(String host) {
    final h = host.toLowerCase();
    return h == 'localhost' || h == '127.0.0.1' || h == '::1';
  }

  /// 从 OpenAI 兼容响应中提取 choices[0].message.content；解析失败返回 null。
  String? _extractContent(String body) {
    try {
      final json = jsonDecode(body) as Map<String, dynamic>;
      final choices = json['choices'] as List<dynamic>?;
      if (choices == null || choices.isEmpty) return null;
      final message = (choices.first as Map<String, dynamic>)['message'];
      if (message is Map<String, dynamic>) {
        final content = message['content'];
        return content is String ? content : null;
      }
      return null;
    } catch (_) {
      return null;
    }
  }

  String _truncate(String text, [int limit = 300]) {
    if (text.length <= limit) return text;
    return '${text.substring(0, limit)}...';
  }
}
