import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'agent_backend.dart';
import 'cc_runner.dart';

/// 远程端点后端：通过 OpenAI 兼容 /chat/completions 协议请求远程服务生成脚本。
class RemoteBackend implements AgentBackend {
  RemoteBackend({
    required this.endpointUrl,
    required this.apiKey,
    String? model,
    http.Client? client,
    this.timeout = const Duration(seconds: 120),
  })  : _model = model,
        _client = client ?? http.Client();

  final String endpointUrl;
  final String apiKey;
  final String? _model;
  final Duration timeout;
  final http.Client _client;
  bool _cancelled = false;

  @override
  String get id => 'remote';

  @override
  String get displayName => 'Remote Endpoint';

  @override
  String? get defaultModel => _model;

  /// 已配置 URL 即视为可用；真正连通性由 execute 的请求结果体现。
  @override
  Future<bool> isAvailable() async => endpointUrl.trim().isNotEmpty;

  @override
  void cancel({String? key}) => _cancelled = true;

  /// 请求 OpenAI 兼容 /chat/completions 端点并提取生成的脚本。
  @override
  Future<CCResult> execute({
    required String task,
    required String software,
    required Map<String, dynamic> capabilities,
    required Map<String, dynamic> state,
    String? model,
    String? scriptLanguage,
    String? key,
  }) async {
    if (_cancelled) return CCResult.failure('Remote endpoint cancelled');
    final prompt = buildCodeBlockPrompt(
      task: task,
      software: software,
      capabilities: capabilities,
      state: state,
      scriptLanguage: scriptLanguage ?? 'javascript',
    );
    final body = {
      if (model != null && model.isNotEmpty) 'model': model,
      'messages': [
        {'role': 'system', 'content': prompt},
        {'role': 'user', 'content': task},
      ],
    };
    try {
      final response = await _client
          .post(
            Uri.parse(_chatCompletionsUrl(endpointUrl)),
            headers: {
              'Content-Type': 'application/json',
              if (apiKey.isNotEmpty) 'Authorization': 'Bearer $apiKey',
            },
            body: jsonEncode(body),
          )
          .timeout(timeout);
      if (_cancelled) return CCResult.failure('Remote endpoint cancelled');
      if (response.statusCode != 200) {
        return CCResult.failure(
            'Remote endpoint error ${response.statusCode}: ${_truncate(response.body)}');
      }
      final content = _extractContent(response.body);
      if (content == null) {
        return CCResult.failure(
            'Remote endpoint returned no script: ${_truncate(response.body)}');
      }
      final script = extractScriptFromMarkdown(content) ?? content.trim();
      if (script.isEmpty) {
        return CCResult.failure('Remote endpoint returned an empty script');
      }
      return CCResult(
        script: script,
        explanation: 'Generated by remote endpoint',
        modelUsed: model ?? _model,
      );
    } catch (e) {
      return CCResult.failure('Remote endpoint request failed: $e');
    }
  }

  /// 以 /chat/completions 结尾的 URL 原样使用，否则追加。
  String _chatCompletionsUrl(String base) {
    final trimmed = base.trim();
    if (trimmed.endsWith('/chat/completions')) return trimmed;
    return '${trimmed.replaceAll(RegExp(r'/+$'), '')}/chat/completions';
  }

  /// 从 OpenAI 兼容响应中提取 choices[0].message.content；解析失败返回 null。
  String? _extractContent(String body) {
    try {
      final json = jsonDecode(body) as Map<String, dynamic>;
      final choices = json['choices'] as List<dynamic>?;
      if (choices == null || choices.isEmpty) return null;
      final message = (choices.first as Map<String, dynamic>)['message'];
      if (message is Map<String, dynamic>) {
        final content = message['content'];
        return content is String ? content : null;
      }
      return null;
    } catch (_) {
      return null;
    }
  }

  String _truncate(String text, [int limit = 300]) {
    if (text.length <= limit) return text;
    return '${text.substring(0, limit)}...';
  }
}
